trigger:
 - master
stages:
 - stage: Build
   displayName: Create build artifact
   jobs:
     - job: BuildArtifact
       pool: MyAubay
       steps:
         - script: C:\Users\skonate\AppData\Local\Programs\UiPath\Studio\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
           displayName: "Build the artifact"
         - publish: $(Build.ArtifactStagingDirectory)           
           artifact: drop
  
 - stage: DeployDEV
   displayName: Deploy build artifact to DEV
   dependsOn: Build
   condition: succeeded()
   jobs:
      - deployment: deployDEV
        displayName: Deploy package to DEV Orchestrator
        pool: MyAubay
        environment: DEV
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@3
              inputs:
                orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
                packagesPath: '$(Pipeline.Workspace)\drop\'
                folderName: 'MyAUBAY'