trigger:
  - master


stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: MyAubay
      steps:
      - task: UiPathPack@3
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop

 

  - stage: DeployDEV
    displayName: Deploy build artifact to DEV
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployDEV
        displayName: Deploy package to DEV Orchestrator
        pool: MyAubay
        environment: DEV
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@3
              inputs:
                orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
                packagesPath: '$(Build.ArtifactStagingDirectory)'
                folderName: 'MyAUBAY'


  - stage: TestDEV
    displayName:  Test After Publish
    dependsOn: DeployDEV
    condition: succeeded()
    jobs:
      - job: TestDEV
        pool: MyAubay
        steps:
          - task: UiPathTest@3
            inputs:
              testTarget: 'TestSet'
              orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
              testSet: 'TEST_SET_2'
              folderName: 'MyAUBAY'
