# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  MyAubay

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathRunJob@3
  inputs:
    orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
    processName: 'MyFirstRobot'
    folderName: 'MyAUBAY'
    jobType: 'TestAutomation'
    user: 'tech\skonate'
    machine: 'TECH-PO22402NN'