trigger:
  - master
variables:
  - group: XYZ

stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: MyAubay
      steps:
      - task: UiPathPack@3
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop

  - stage: Assest
    displayName: Create Assests
    jobs:
      - job: CreateAssests
        pool: MyAubay
        steps:
        - task: UiPathAssets@3
          inputs:
            orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
            folderName: 'MyAUBAY'
            assetActionType: 'Deploy'
            csvFile: '$(Build.SourcesDirectory)\Data\Assests.csv'


  - stage: DeployDEV
    displayName: Deploy build artifact to DEV
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployDEV
        displayName: Deploy package to DEV Orchestrator
        pool: MyAubay
        environment: DEV
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@3
              inputs:
                orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
                packagesPath: '$(Pipeline.Workspace)\drop\'
                folderName: 'MyAUBAY'
                

  - stage: WorkflowAnalyser
    displayName: RunWorkflow Analyser
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: WorkflowAnalyser
        displayName: AnalyseProject Using Worflow Cli
        pool: MyAubay
        steps:
        - task: PowerShell@2
          inputs:
            targetType: filePath
            filePath: $(Build.SourcesDirectory)\Data\Workflow-Analyser-CLI-Script.ps1
            arguments: > # Use to avoid newline characters in multiline string
               -ProjectFilePath $(Build.SourcesDirectory)\project.json
               -ExecutableFilePath "CC:\Users\skonate\AppData\Local\Programs\UiPath\Studio\UiPath.Studio.CommandLine.exe"
               -OutputFilePath '$(Pipeline.workspace)\drop\workflow-Analysis.json'
            workingDirectory: 'Analyse Project'
          displayName: 'Analyse Project'


  - stage: TestDEV
    displayName:  Test After Publish
    dependsOn: DeployDEV
    condition: succeeded()
    jobs:
      - job: TestDEV
        pool: MyAubay
        steps:
          - task: UiPathTest@3
            inputs:
              testTarget: 'TestSet'
              orchestratorConnection: 'Con_AzureDevOps_Orchestrator'
              testSet: 'TEST_SET_AUTHENTIFICATION'
              folderName: 'MyAUBAY'
              testReportDestination: '$(Pipeline.Workspace)\drop\'